### ISSUE TITLE
porting improvements implemented here to c.purgebyid

### ISSUE THREAD

**Issue by mamico** [collective/collective.xkey#2]
@pgrunewald kudos for this work. But I think that we could be putting forces together, moving your improvements to collective.purgebyid. At the end of the day, I think that all your improvements could coexist in the original product.

If you agree, I prepare a PR in collective.purgebyid, with your work and I will assign it to you as reviewer.

**Comment by pgrunewald** [comment]
I was pondering about adding the changes to collective.purgebyid myself, but was not sure what is the most elegant way doing so. There are some points that should be able to be changed:

- The HTTP header needs to be changeable (by the name and how the IDs are joined together)
- In the adapter for IPubAfterTraversal you should be able to decide, whose objects' IUUDs I want to have involved (parents from request AND/OR the published object)

This might be achieved in some sort of settings, by adding a module-wide variable in collective.purgebyid, that can be changed from the integrator's own code. 

Anyhow, I would gladly review any PR, that incorporates the additions to collective.purgebyid. :+1:

**Comment by mamico** [comment]
@pgrunewald Looking deeper, I saw that it is simple to use the xkey approach without introducing any changes to the Python code: https://github.com/collective/collective.purgebyid#varnish-with-xkey-varnish-module and https://github.com/collective/collective.purgebyid/blob/master/.github/varnish/tests/test02.vtc

This solution, in my opinion, has the advantage of leaving the choice in the varnish configuration part, without any other customization / configuration on the plone side. Do you agree ?

On the other hand, I found the "utility browser view mark_involved" useful and will try to include it in collective.purgebyid.

**Comment by pgrunewald** [comment]
Having the same code base on the Plone side and let Varnish have the choice how to use the response header is indeed favorable. So I agree there. Kudos for providing tests with Varnish!

Apart from the browser view, maybe some other mini changes are interesting as well. So I got rid of NOID, because it does not serve any purpose when I can just return (empty) lists. After further inspection of the current API, empty lists should work as well. So there is no difference for my current adapter implementations. :)

Conclusion: I will deprecate this add-on and promote c.purgebyid in the README.

**Comment by pgrunewald** [comment]
Okay, I updated the README effectively deprecating this add-on. If anyone is reading this comment, you may continue using this add-on and it should still work, but it is not supported.
